version: "3.9"
services:
  database:
    image: postgres:12-alpine
    env_file:
      - .env
    volumes:
      - ./.docker/volumes/database:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./.docker/seedrs/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - ./seedrs:/seedrs
    ports:
      - "3000:3000"
    depends_on:
      - database